### ISSUE TITLE
JOSS paper: VISA description

### ISSUE THREAD

**Issue by MatthieuDartiailh** [SwiftVISA/SwiftVISASwift#3]
I am bothered by the strong link made between VISA and SCPI. VISA provides an abstraction over the physical bus used for communication but does not mandate the format of the message circulating on that bus (except for IEEE 488.2 messages). In particular VISA also provide access to register based instruments for which SCPI makes no sense at all. 

I am not sure how this should be phrased to be palatable for the reader but I believe that such a strong implicit coupling should be avoided as it tends to create some confusions.

https://github.com/openjournals/joss-reviews/issues/4752

**Comment by OHildreth** [comment]
**Authors’ Response to Reviewer Comment**
Thank you, you are correct.  We have removed references to SCPI from the document.

**Original Text**
The Virtual Instrument Software Architecture (VISA)[@NI-VISA_download, @wiki_VISA] is a simple Application Programming Interface (API) ~~implementing the Standard Commands for Programmable Instruments (SCPI)[@SCPI]~~ to control test and measurement instrumentation from a computer.

**Updated Text**
The Virtual Instrument Software Architecture (VISA)[@NI-VISA_download, @wiki_VISA] is a simple Application Programming Interface (API) to control test and measurement instrumentation from a computer.

**Comment by MatthieuDartiailh** [comment]
The edit looks good to me
