### ISSUE TITLE
JOSS Paper question: binding to other VISA implementation on Linux

### ISSUE THREAD

**Issue by MatthieuDartiailh** [SwiftVISA/SwiftVISASwift#4]
The package is supposed to compile on Linux where other vendor provide VISA implementations (Keysight). Could SwiftVISA bind to those pre-compiled binaries ?

This is mostly for my own education.

**Comment by OHildreth** [comment]
We haven't tested that yet.  We've only tested on macOS.  I'm not familiar with Linux systems at all and it seems like opening a new bag-of-worms.

However, I would be more than happy to work with you or someone with Linux experience to test this out.  I could also support a "Field Session" project here at Colorado School of Mines to have some CS students try to get it up and running.

**Comment by MatthieuDartiailh** [comment]
Thanks. I was just curious since on Linux you may not have the same kernel issues you have on MacOS and you could use reliably a vendor implemented VISA. This is not a blocker for the paper but a small mention could be added since it seems like a legitimate question.

**Comment by OHildreth** [comment]
Thanks.  This is a good idea and I will use it as a project for next summer's Computer Science Field Session here at Mines.  I've added the following text to the _Current Limitations and Future Work_ section:


_We are planning to host an additional Computer Science Field Session Project at Colorado School of Mines in 2023 to expand either `SwiftVISA` or `SwiftVISASwift` to a Swift-supported Linux platform._
