### ISSUE TITLE
JOSS paper: typos 

### ISSUE THREAD

**Issue by MatthieuDartiailh** [SwiftVISA/SwiftVISASwift#5]
concurrancy -> concurrency
line 188 geoemtry -> geometry

https://github.com/openjournals/joss-reviews/issues/4752

**Comment by OHildreth** [comment]
Thank you for pointing these out.  I’m sorry I didn’t catch them earlier, I didn’t notice that the Markdown editor I was using didn’t include spell check.  I imported the manuscript into Word and fixed a dozen or so misspellings and typos.  Additionally, I had two other students not familiar with the manuscript or topic review the manuscript for clarity and typos.
